sudo: false
language: node_js
node_js: 14.15.3
script:
- npm run audit
- npm run snyk
- npm run lint
env:
  SNYK_TOKEN:
    secure: WL/zpwLGcUrw8tSC6u6rbMpD2+jRU16zlKkDaFypTyOSIqHTgu168mLv3QLeu4daMa9DgduJPo0pWWPjXRj2i09aytL/Z1LlB77uoB3dTFLl7fFolCWx03SkbPxODCDkvqmScq9usZbiAl5kQgTFCsigIQZ9m57+DPfdEo5nMvs+FBcBpJk+r0tR0dgKFk+62zXiGvr20yun0YsEEUgATh6XTgNh2D9cbQiGSmcGGygGGMdX/5NIAhctLXinxh4GX5ru/4CDZcxHRrxi/19dZw7oFAfUyptjuGDxRMSypGiMl582v0aKoEhh+Ay1iwLeht1a86LB7jNMh2DbCNFpugrYcUGWCfkweDZReOpFNHYDOTlvt3/elgXVvL6Ms/4R2I1yXnKYKTltmr0sjlcQh+++EDwrIns9nnZC+ec1eo9miAgQmtXWg1i4M5RdMhbOTC9KVqgKrSp+99qlUMN6KAzfJv6dv1tMBxdYVuWI8ve7qlqtzlQExH5bKhitwXae7/J0vNLVi99FiJi3m5N+M8wr9UgqgiHO9zYzbaIr+CfoL6bMPxBanR3pzogEW7VIaanAKwJOua1EYmhKbQAmqk+Xl42/TGxm0tH1ENVEC6YWWzLVWm3UU/F95Tc9qD/PICHA0wb7uXL5eNF71e2/b5lt7jFwWsJI43GnRWk0jwU=
