sudo: false
language: node_js
node_js: 14.15.3
script:
  - npm run audit
  - npm run snyk
  - npm run lint
env:
  SNYK_TOKEN:
    - secure: MwpEQDZIN+MpG3gfuo8F4UaxEieD1nIx/uukKM6JZD1ACKw016Z/PXXXXw/pjgqom2tFBW2ofD0T/E6fAW5JZ//BI54HOJVtV7N9WTGgNQJ+x3ikmRtKk56fXAi43Ue7eP5Ginsz2MW/LLpm2HB6bKbMSI3QmjyTVVI16Pz827KqbGiQame/IjsQC0UeyrAeP67cIBUoUPZ8rC2Y3X6uOTwkzo71Pro+zh4IP3+Vnvo7qB1M0bt7WqA4Js8ZBAy3J8brpLHl+ieHZIqM5iSFHtnx70fwTa0TlGoTvvlVzGtddOW2f4u2cr6gSsg73jyIlkl7dl4CvngnaKDJQYlbvLkVNeie+m/h7Fzrgy36K9y/NM9n+kBWR/Vux05anaafbTHolsa/IxC0bzjOgqnPYUmBE3XcsUIv87oD00gQVyO1lNA/DbVfm0d48gEVZSYE/yp6Lb597KIZJrY4FW0jzTWkwAciwdW035jl6ycU0UMjEBxVBFh9pSZB4VCab7IM03h/vyDRiNwlExUF0CAKX5gHklxFQDyztvoM/zlrwkzOfGQcy71G4Q30NC3YYrmI3r3iCPoJ26d05plfp4AVcFr7ZN/kmJvwKMN5KX9GKpsrDvUK69vXJkXTBAjK+s1DzX+rqzYRQHY1Q6TUKBdcWdmp7QVBbTWsN30nW0m3FCs=
