sudo: false
language: node_js
node_js: 14.15.3
script:
- npm run audit
- npm run snyk
- npm run lint
- npm run test
after_success: npm run coveralls
before_deploy:
- npm run build
deploy:
  provider: npm
  email: adonisv79@gmail.com
  skip_cleanup: true
  api_key:
    secure: a/2GzWRad98/8A0uDsKfkBegNdVx8ETO9O/WzsZB9xGVhehZ/MK0dYwpKW/XE87ew5lqA/dQOmKKqEflxfsLtHDorstMFwq9M17l1vX/UznqYcxsFpV6W+L1jI/6jyoOGsB2k2M9LgYfUtkQj3s6aVMx59vBquG5MXi1usstg2mnZ1mF+ormorlNEX+E7/9I5uEHtaXE2ePUXjvA5EsVFkLndvvWffeP9L966Okd/Wq05smWs8zxOCItdmwPecQB1o2UWQfAB/TSxZGyU5g7/jkbBQ8Nms3Hkr45EuyseZG9KPyq5PuaXkxndKe7jNHmXtVZjujl9qWSknd5tgSZrzkBeB1f1ePGN2h8lt66MukFTAWuf/Yapya9zKMHLxb5OLcyewZ2AjsJ7yQNqbPm+MX9gc5ryYHcJ24TzbASYuoMEB1KdAZJb49ST5OJ1ZX1/kbSYlGt05XvGyGMmlied6+lZa50xNcNGHFS+PyrNMwecOmsFhxtlXCAgAKuJBjW94wKe7ni6noCIOMOppJ1cB7t/jA+gOk0/aMSxnVLA2Eg5xQr7lmSjCh9gNueIZ1G8zzvqqWrNqLkau7Imi5yAf5XtKL/iwEk19MPUhjlVb+PHrl+bmfzzzH+8g4hPZqBxxnbHERN7A9i6foZH+xf7OD0qt/DXmsDHmgRaRdNC78=
  on:
    tags: true
    branch: master
